// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "BashCut",
    platforms: [.macOS(.v14)],
    // Single source of truth for targets: the Xcode project (project.yml) links these library products
    // instead of declaring its own copies of the core modules.
    products: [.executable(name: "BashCutApp", targets: ["BashCut"]),
               .executable(name: "bashcut", targets: ["BashCutCLI"]),
               .executable(name: "bashcut-mcp", targets: ["BashCutMCP"]),
               // Core plugin copied into BashCut.app/Contents/PlugIns/bashcut.audio-analysis/bin/provider.
               .executable(name: "bashcut-audio-analysis", targets: ["bashcut-audio-analysis"]),
               .library(name: "BashCutAudioAnalysis", targets: ["BashCutAudioAnalysis"]),
               // Core plugin copied into BashCut.app/Contents/Resources/Plugins/bashcut.vision/bin/provider.
               .executable(name: "bashcut-vision", targets: ["bashcut-vision"]),
               .library(name: "BashCutVisionAnalysis", targets: ["BashCutVisionAnalysis"]),
               .library(name: "BashCutEngine", targets: ["BashCutEngine"]),
               .library(name: "BashCutStorage", targets: ["BashCutStorage"]),
               .library(name: "BashCutAutomation", targets: ["BashCutAutomation"]),
               .library(name: "BashCutAgent", targets: ["BashCutAgent"]),
               .library(name: "BashCutPlugins", targets: ["BashCutPlugins"]),
               .library(name: "BashCutDocument", targets: ["BashCutDocument"]),
               .library(name: "BashCutTestSupport", targets: ["BashCutTestSupport"])],
    dependencies: [.package(path: "Packages/BashCutCore"),
                   .package(url: "https://github.com/pointfreeco/swift-snapshot-testing", from: "1.17.0"),
                   .package(url: "https://github.com/migueldeicaza/SwiftTerm", from: "1.20.0"),
                   .package(url: "https://github.com/apple/swift-argument-parser", from: "1.5.0"),
                   .package(url: "https://github.com/modelcontextprotocol/swift-sdk.git", exact: "0.12.1")],
    targets: [
        .target(name: "BashCutEngine", dependencies: [.product(name: "BashCutProject", package: "BashCutCore")],
                path: "BashCut/Core/Engine"),
        .target(name: "BashCutStorage", dependencies: [.product(name: "BashCutProject", package: "BashCutCore")],
                path: "BashCut/Core/Storage"),
        .target(name: "BashCutAutomation", dependencies: [.product(name: "BashCutProject", package: "BashCutCore")],
                path: "BashCut/Core/Automation"),
        .target(name: "BashCutAgent", dependencies: [.product(name: "BashCutProject", package: "BashCutCore"),
            .product(name: "BashCutPlugin", package: "BashCutCore")], path: "BashCut/Core/Agent"),
        .target(name: "BashCutPlugins", dependencies: [.product(name: "BashCutProject", package: "BashCutCore"),
            .product(name: "BashCutPlugin", package: "BashCutCore")], path: "BashCut/Core/Plugins"),
        .target(name: "BashCutDocument", dependencies: ["BashCutEngine", "BashCutPlugins", "BashCutAutomation", "BashCutStorage",
            .product(name: "BashCutImport", package: "BashCutCore"),
            .product(name: "BashCutProject", package: "BashCutCore"),
            .product(name: "BashCutInterchange", package: "BashCutCore"),
            .product(name: "BashCutPlugin", package: "BashCutCore")], path: "BashCut/Core/Services"),
        .executableTarget(name: "bashcut-bench", dependencies: ["BashCutEngine",
            .product(name: "BashCutProject", package: "BashCutCore")], path: "Tools/Bench"),
        .executableTarget(name: "bashcut-fixtures", dependencies: ["BashCutTestSupport"], path: "Tools/Fixtures"),
        .executableTarget(name: "BashCutCLI", dependencies: ["BashCutAutomation",
            .product(name: "ArgumentParser", package: "swift-argument-parser")], path: "CLI"),
        .executableTarget(name: "BashCutMCP", dependencies: ["BashCutAutomation",
            .product(name: "MCP", package: "swift-sdk")], path: "MCPBridge"),
        // Core plugins: separate processes like any plugin, built with the app (Plugins/<name>/).
        .target(name: "BashCutAudioAnalysis", path: "Plugins/audio-analysis/Sources/Analysis"),
        .executableTarget(name: "bashcut-audio-analysis", dependencies: ["BashCutAudioAnalysis"],
                          path: "Plugins/audio-analysis/Sources/Provider"),
        .target(name: "BashCutVisionAnalysis", path: "Plugins/vision/Sources/Analysis"),
        .executableTarget(name: "bashcut-vision", dependencies: ["BashCutVisionAnalysis"],
                          path: "Plugins/vision/Sources/Provider"),
        .executableTarget(name: "BashCut", dependencies: [
            "BashCutEngine", "BashCutStorage", "BashCutDocument", "BashCutAgent", "BashCutAutomation", "BashCutPlugins",
            .product(name: "BashCutProject", package: "BashCutCore"),
            .product(name: "BashCutImport", package: "BashCutCore"),
            .product(name: "BashCutInterchange", package: "BashCutCore"),
            .product(name: "BashCutPlugin", package: "BashCutCore"),
            .product(name: "SwiftTerm", package: "SwiftTerm")], path: "BashCut",
            exclude: ["Core/Engine", "Core/Storage", "Core/Agent", "Core/Automation", "Core/Plugins", "Core/Services",
                      "Info.plist", "BashCut.entitlements", "Resources"]),
        // Tests: one target per module plus shared fixtures (generated media, scratch folders, synthetic audio).
        .target(name: "BashCutTestSupport", path: "Tests/BashCutTestSupport"),
        .testTarget(name: "BashCutEngineTests", dependencies: ["BashCutEngine", "BashCutTestSupport",
            .product(name: "BashCutProject", package: "BashCutCore"),
            .product(name: "SnapshotTesting", package: "swift-snapshot-testing")], exclude: ["__Snapshots__"]),
        .testTarget(name: "BashCutStorageTests", dependencies: ["BashCutStorage", "BashCutTestSupport",
            .product(name: "BashCutProject", package: "BashCutCore")]),
        .testTarget(name: "BashCutAutomationTests", dependencies: ["BashCutAutomation", "BashCutEngine", "BashCutTestSupport",
            .product(name: "BashCutProject", package: "BashCutCore")]),
        .testTarget(name: "BashCutAgentTests", dependencies: ["BashCutAgent", "BashCutTestSupport",
            .product(name: "BashCutProject", package: "BashCutCore"), .product(name: "BashCutPlugin", package: "BashCutCore")]),
        .testTarget(name: "BashCutPluginsTests", dependencies: ["BashCutPlugins", "BashCutAgent", "BashCutAutomation", "BashCutTestSupport",
            .product(name: "BashCutProject", package: "BashCutCore"),
            .product(name: "BashCutPlugin", package: "BashCutCore")]),
        .testTarget(name: "BashCutAudioAnalysisTests", dependencies: ["BashCutAudioAnalysis"]),
        .testTarget(name: "BashCutVisionAnalysisTests", dependencies: ["BashCutVisionAnalysis", "BashCutTestSupport"]),
        .testTarget(name: "BashCutDocumentTests", dependencies: ["BashCutDocument", "BashCutEngine", "BashCutStorage",
            "BashCutAudioAnalysis", "BashCutPlugins",
            "BashCutAutomation", "BashCutTestSupport",
            .product(name: "BashCutProject", package: "BashCutCore"),
            .product(name: "BashCutInterchange", package: "BashCutCore")]),
    ]
)
