import BashCutEngine
import BashCutPlugin
import Foundation

/// What BashCut keeps on disk outside the user's projects and media, with sizes, for Settings › Storage and
/// `storage get`. Measuring walks folders, so call `measure` off the main actor.
public struct StorageEntry: Sendable, Identifiable, Equatable {
    public enum Kind: String, Sendable {
        /// One installed plugin's folder (code); a dev link counts as the link only.
        case plugins
        /// One plugin's `BASHCUT_PLUGIN_DATA` (environments, settings): deleting it means setting the plugin up again.
        case pluginData = "plugin-data"
        /// One plugin's `BASHCUT_PLUGIN_CACHE` (downloaded models): fetched again when needed.
        case pluginCache = "plugin-cache"
        /// `BASHCUT_SHARED_DATA`, runtimes several plugins use (Python installs): deleting it means setting those
        /// plugins up again.
        case sharedData = "shared-data"
        /// `BASHCUT_SHARED_CACHE`, downloads several plugins use (uv's package cache). Environments made from it
        /// keep their own copy (APFS clones), so clearing it is safe.
        case sharedCache = "shared-cache"
        /// The saved copy of the plugin registry.
        case registry
        /// The open project's preview proxies (`.bashcut/cache/proxies`), made again on demand.
        case proxies
        /// Reusable PCM produced for speed ramps; regenerated by preview/export as needed.
        case rampAudio = "ramp-audio"
        /// Automation audit log; kept as a record, never cleared from here.
        case audit
    }

    public let kind: Kind
    public let pluginID: String?
    public let url: URL
    public let bytes: Int64
    public var id: String { kind.rawValue + (pluginID.map { ":" + $0 } ?? "") }
    public var clearable: Bool { kind != .plugins && kind != .audit }
}

/// Everything one plugin keeps on disk: its code, data and cache entries, for one row per plugin.
public struct PluginStorage: Sendable, Identifiable, Equatable {
    public let pluginID: String
    /// Code first, then data, then cache.
    public let entries: [StorageEntry]
    public var id: String { pluginID }
    public var bytes: Int64 { entries.reduce(0) { $0 + $1.bytes } }
    /// False when only data or a cache is left behind by a removed plugin.
    public var installed: Bool { entries.contains { $0.kind == .plugins } }
}

public enum StorageUsage {
    public static var supportFolder: URL {
        FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("BashCut", isDirectory: true)
    }

    public static var registryFolder: URL { PluginFolders.registryCache }

    public static func proxiesFolder(projectRoot: URL) -> URL {
        projectRoot.appendingPathComponent(ProxyMediaSource.folder, isDirectory: true)
    }

    /// Every entry that exists: each installed plugin's folder, data and caches for each plugin that has some, and the
    /// shared plugin runtimes when they hold something.
    public static func measure(projectRoot: URL?, pluginsFolder: URL,
                               pluginDataRoot: URL = PluginFolders.dataRoot, pluginCacheRoot: URL = PluginFolders.cacheRoot,
                               supportRoot: URL = supportFolder, registryRoot: URL = registryFolder) -> [StorageEntry] {
        var entries: [StorageEntry] = []
        let manager = FileManager.default
        func children(_ root: URL) -> [String] {
            // Hidden items (`.previous`) and the shared folders (`_shared`) are not plugins.
            ((try? manager.contentsOfDirectory(atPath: root.path)) ?? []).filter { !$0.hasPrefix(".") && !$0.hasPrefix("_") }
        }
        let installed = Set(children(pluginsFolder))
        for id in installed.union(children(pluginDataRoot)).union(children(pluginCacheRoot)).sorted() {
            if installed.contains(id) {
                let url = pluginsFolder.appendingPathComponent(id)
                entries.append(StorageEntry(kind: .plugins, pluginID: id, url: url, bytes: size(of: url)))
            }
            for (kind, url) in [(StorageEntry.Kind.pluginData, pluginDataRoot.appendingPathComponent(id)),
                               (.pluginCache, pluginCacheRoot.appendingPathComponent(id))]
            where manager.fileExists(atPath: url.path) {
                // Every plugin gets empty folders; only ones holding something are worth a row.
                let bytes = size(of: url)
                if bytes > 0 { entries.append(StorageEntry(kind: kind, pluginID: id, url: url, bytes: bytes)) }
            }
        }
        for (kind, url) in [(StorageEntry.Kind.sharedData, pluginDataRoot.appendingPathComponent(PluginFolders.sharedName)),
                           (.sharedCache, pluginCacheRoot.appendingPathComponent(PluginFolders.sharedName))] {
            let bytes = size(of: url)
            if bytes > 0 { entries.append(StorageEntry(kind: kind, pluginID: nil, url: url, bytes: bytes)) }
        }
        entries.append(StorageEntry(kind: .registry, pluginID: nil, url: registryRoot, bytes: size(of: registryRoot)))
        if let projectRoot {
            let proxies = proxiesFolder(projectRoot: projectRoot)
            entries.append(StorageEntry(kind: .proxies, pluginID: nil, url: proxies, bytes: size(of: proxies)))
        }
        if let projectRoot {
            let audio = ProjectCache.url(.rampAudio, projectRoot: projectRoot)
            entries.append(StorageEntry(kind: .rampAudio, pluginID: nil, url: audio, bytes: size(of: audio)))
        }
        let audit = supportRoot.appendingPathComponent("audit.jsonl")
        entries.append(StorageEntry(kind: .audit, pluginID: nil, url: audit, bytes: size(of: audit)))
        return entries
    }

    /// The plugin entries grouped by plugin, largest total first (ties by ID).
    public static func byPlugin(_ entries: [StorageEntry]) -> [PluginStorage] {
        let order: [StorageEntry.Kind] = [.plugins, .pluginData, .pluginCache]
        return Dictionary(grouping: entries.filter { $0.pluginID != nil }) { $0.pluginID ?? "" }
            .map { id, group in
                PluginStorage(pluginID: id, entries: group.sorted {
                    (order.firstIndex(of: $0.kind) ?? order.count) < (order.firstIndex(of: $1.kind) ?? order.count)
                })
            }
            .sorted { $0.bytes != $1.bytes ? $0.bytes > $1.bytes : $0.pluginID < $1.pluginID }
    }

    /// Allocated bytes of a file or folder (links not followed); 0 when it does not exist.
    public static func size(of url: URL) -> Int64 {
        let keys: Set<URLResourceKey> = [.totalFileAllocatedSizeKey, .isSymbolicLinkKey, .isDirectoryKey]
        guard let values = try? url.resourceValues(forKeys: keys) else { return 0 }
        if values.isDirectory != true { return Int64(values.totalFileAllocatedSize ?? 0) }
        guard let enumerator = FileManager.default.enumerator(at: url, includingPropertiesForKeys: Array(keys)) else { return 0 }
        var total: Int64 = 0
        for case let item as URL in enumerator {
            let itemValues = try? item.resourceValues(forKeys: keys)
            if itemValues?.isSymbolicLink == true { continue }
            total += Int64(itemValues?.totalFileAllocatedSize ?? 0)
        }
        return total
    }

    /// Deletes an entry's folder contents (the folder itself is recreated empty when it is a root BashCut expects).
    public static func clear(_ entry: StorageEntry) throws {
        guard entry.clearable else { throw StorageUsageError("\(entry.kind.rawValue) cannot be cleared") }
        let manager = FileManager.default
        guard manager.fileExists(atPath: entry.url.path) else { return }
        try manager.removeItem(at: entry.url)
    }
}

public struct StorageUsageError: LocalizedError {
    public let message: String
    public init(_ message: String) { self.message = message }
    public var errorDescription: String? { message }
}
