#!/usr/bin/env python3
"""Regenerates BashCut/Models/Acknowledgements.swift: the license texts of every package linked into a shipped
binary (app, `bashcut`, `bashcut-mcp`), shown in the About panel. Distributing a build requires them.

    scripts/update-acknowledgements.py           # rewrite the file
    scripts/update-acknowledgements.py --check   # fail if it is stale or a resolved package is unclassified

Versions come from the Package.resolved files and texts from the resolved checkouts (`swift package resolve`
fetches them). Every resolved package must be listed in SHIPPED or NOT_SHIPPED below, so a new dependency
forces a decision; docs/reference/third-party.md records which binary links what.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "BashCut/Models/Acknowledgements.swift"
RESOLVED = [
    (ROOT / "Package.resolved", ROOT / ".build/checkouts"),
    (ROOT / "Packages/BashCutCore/Package.resolved", ROOT / "Packages/BashCutCore/.build/checkouts"),
]
# identity -> (display name, license name), in display order.
SHIPPED = {
    "swiftterm": ("SwiftTerm", "MIT"),
    "swift-sdk": ("MCP Swift SDK", "MIT and Apache-2.0"),
    "eventsource": ("EventSource", "MIT"),
    "swift-log": ("Swift Logging API", "Apache-2.0"),
    "swift-system": ("Swift System", "Apache-2.0 with Runtime Library Exception"),
    "swift-argument-parser": ("Swift Argument Parser", "Apache-2.0 with Runtime Library Exception"),
    "swift-collections": ("Swift Collections", "Apache-2.0 with Runtime Library Exception"),
}
NOT_SHIPPED = {
    "swift-nio": "resolved for the MCP SDK's conformance tools, not linked",
    "swift-atomics": "pulled in by swift-nio, not linked",
    "swift-snapshot-testing": "tests only",
    "swift-custom-dump": "tests only",
    "xctest-dynamic-overlay": "tests only",
    "swift-syntax": "tests only",
}
NOTICE_NAMES = ("LICENSE", "LICENSE.txt", "LICENSE.md", "NOTICE", "NOTICE.txt", "NOTICE.md")


def collect():
    pins = {}
    for resolved, checkouts in RESOLVED:
        for pin in json.loads(resolved.read_text())["pins"]:
            folder = pin["location"].rstrip("/").split("/")[-1].removesuffix(".git")
            pins.setdefault(pin["identity"], (pin, checkouts / folder))
    unclassified = sorted(set(pins) - set(SHIPPED) - set(NOT_SHIPPED))
    if unclassified:
        sys.exit(f"error: classify {', '.join(unclassified)} in SHIPPED or NOT_SHIPPED in {Path(__file__).name}")
    entries = []
    for identity, (name, license_name) in SHIPPED.items():
        if identity not in pins:
            sys.exit(f"error: {identity} is in SHIPPED but no longer resolved")
        pin, checkout = pins[identity]
        texts = [(checkout / file).read_text().strip() for file in NOTICE_NAMES if (checkout / file).is_file()]
        if not texts:
            sys.exit(f"error: no license file in {checkout}; run `swift package resolve`")
        version = pin["state"].get("version") or pin["state"]["revision"][:12]
        url = pin["location"].removesuffix(".git")
        entries.append((name, version, url, license_name, "\n\n".join(texts)))
    return entries


def swift_string(text):
    assert '"""#' not in text
    return '#"""\n' + "\n".join(("            " + line).rstrip() for line in text.splitlines()) + '\n            """#'


def render(entries):
    lines = [
        "// Generated by scripts/update-acknowledgements.py from the resolved packages; do not edit.",
        "// License texts are kept verbatim; .swiftlint.yml excludes this file.",
        "",
        "/// Third-party packages linked into the shipped app, CLI and MCP server, with their license texts.",
        "enum Acknowledgements {",
        "    struct Package {",
        "        let name: String",
        "        let version: String",
        "        let url: String",
        "        let license: String",
        "        let text: String",
        "    }",
        "",
        "    static let packages: [Package] = [",
    ]
    for name, version, url, license_name, text in entries:
        lines += [
            "        Package(",
            f'            name: "{name}", version: "{version}", url: "{url}", license: "{license_name}",',
            f"            text: {swift_string(text)}",
            "        ),",
        ]
    lines += ["    ]", "}", ""]
    return "\n".join(lines)


def main():
    content = render(collect())
    if "--check" in sys.argv[1:]:
        if not OUTPUT.is_file() or OUTPUT.read_text() != content:
            sys.exit(f"error: {OUTPUT.relative_to(ROOT)} is stale; run scripts/update-acknowledgements.py")
        print("acknowledgements are up to date")
        return
    OUTPUT.write_text(content)
    print(f"Updated {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
